on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Static Checks (Lint, Format, Typecheck)
  static-checks:
    name: Static Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npx biome ci
      - run: npm run typecheck
      - run: npm run attw

  # Vitest
  tests:
    name: Tests on Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [20, 22, 24]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm run test:cov
